---
cilium_vars:
  release:
    cli:
      file: cilium-linux-arm64.tar.gz
      repository:
        name: cilium-cli
        org: cilium
      version: v0.16.7
    gateway_api:
      file: experimental-install.yaml
      repository:
        name: gateway-api
        org: kubernetes-sigs
      version: v1.1.0
    hubble:
      file: hubble-linux-arm64.tar.gz
      repository:
        name: hubble
        org: cilium
      version: v0.13.4
